options:
  service_type:
    type: string
    default: signing
    description: Which service to run - signing or admin or system-user
  keystore_secret:
    type: string
    default: abcdefg1234567890
    description: Secret code to encrypt the auth-key hash
  proxy:
    type: string
    default: ""
    description: Proxy server for accessing the Snap Store
  csrf_auth_key:
    type: string
    default: "2E6ZYnVYUfDLRLV/ne8M6v1jyB/376BL9ORnN3Kgb04uSFalr2ygReVsOt0PaGEIRuID10TePBje5xdjIOEjQQ=="
    description: 32 bytes long key to protect server from cross site request forgery attacks
  environment_variables:
    type: string
    default: ""
    description: Blank separated key=value strings representing env vars
  payload:
    type: string
    default: ""
    description: Swift container object. This is the tgz file holding binaries and service configuration
  swift_container:
    type: string
    default: "serial-vault.canonical.com"
    description: Swift container from where download the service payload
  url_host:
    type: string
    default: serial-vault:443
    description: Return URL of the service (needed for OpenID) without the protocol schema
  enable_user_auth:
    type: boolean
    default: true
    description: Enable user authentication using Ubuntu SSO
